// WEEK 1
// const testData = [
//     {question: "In the figure above, The bowling ball is dropped from a boat so that it strikes the surface of a lake with a speed of 25 ft/s, if the ball has an acceleration of a=10 - 0.9v^2 when in the water, what is the velocity of the ball when it strikes the bottom of the lake ?",
//         option1: "3.33 ft/s",
//         option2: "4.29 ft/s",
//         option3: "1.23 ft/s",
//         option4: "5.45 ft/s",
//         correctAns: "3.33 ft/s",
//     },
//     {question: "In the figure above, The space-shuttle payload module weighs 100lb when resting on the surface of the earth at a latitude of 45o north. Find the mass of the module.",
//         option1: "66.2 kg",
//         option2: "20.7 kg",
//         option3: "45.4 kg",
//         option4: "70.1 kg",
//         correctAns: "45.4 kg",
//     },
    // {question: "In the figure above, The speed of the joger can be approximated by v=7.5(1-0.04x)^0.3 where v and x are in mi/h and miles respectively, determine the distance the jogger has run when t=1h (Given that x=0 when t=0).",
    //     option1: "12.05 mi",
    //     option2: "7.15 mi",
    //     option3: "1.39 mi",
    //     option4: "15.50 mi",
    //     correctAns: "7.15 mi",
    // },
    // {question: "In the figure above, The truck travels 220m in 10s while being deccelerated at a constant rate of 0.6m/s^2, determine the truck's final velocity.",
    //     option1: "25.91 m/s",
    //     option2: "20.29 m/s",
    //     option3: "23.91 m/s",
    //     option4: "19.00 m/s",
    //     correctAns: "19.00 m/s",
    // },
//     {question: "In the figure above, Assuming a uniform acceleration of 11 ft/s^2 and knowing that the speed of a car as it passes A is 30mi/h, determine the speed of the car as it passes B.",
//         option1: "27.1 mi/h",
//         option2: "20.7 mi/h",
//         option3: "50.4 mi/h",
//         option4: "58.1 mi/h",
//         correctAns: "50.4 mi/h",
//     },
//     {question: "In the figure above, The sprinter in a 100m race accelerates uniformly for the first 35m and then runs with constant velocity, determine the sprinter's final velocity if his time for the first 35m is 5.4s",
//         option1: "12.96 m/s",
//         option2: "10.41 m/s",
//         option3: "2.40 m/s",
//         option4: "18.87 m/s",
//         correctAns: "12.96 m/s",
//     },
//     {question: "In the figure above, Slider block A moves to the left with a constant velocity of 6m/s, determine the velocity of  block B.",
//         option1: "4m/s downwards",
//         option2: "3m/s upwards",
//         option3: "0.5m/s downwards",
//         option4: "2m/s upwards",
//         correctAns: "2m/s upwards",
//     },
//     {question: "In the figure above, The 20lb concrete block A is released from rest in the position shown and pulls the 400lb log up to the 30o ramp, what is the velocity of the block as it hits the ground at B if the coefficient of static friction between the log and ramp is 0.5 ?",
//         option1: "12.46 ft/s",
//         option2: "15.27 ft/s",
//         option3: "34.42 ft/s",
//         option4: "58.11 ft/s",
//         correctAns: "15.27 ft/s",
//     },
    // {question: "In the figure above, The motorist enters a freeway at 45km/h and accelerates uniformly to 99km/h. From the odometer in the car, the motorist knows that she travelled 0.2km while accelerating, determine the acceleration of the car.",
    //     option1: "1.500 m/s^2",
    //     option2: "2.007 m/s^2",
    //     option3: "4.320 m/s^2",
    //     option4: "1.841 m/s^2",
    //     correctAns: "1.500 m/s^2",
    // },
    // {question: "In the figure above, As Relay runner A enters the 20m long exchange zone with speed of 12.9m/s, he begins to slow down. Hands the baton to runner B, 1.82s later as they leave the exchange zone with the same velocity. What is the uniform acceleration of runner A ?",
    //     option1: "2.06 m/s^2",
    //     option2: "2.71 m/s^2",
    //     option3: "-2.10 m/s^2",
    //     option4: "-2.31 m/s^2",
    //     correctAns: "-2.10 m/s^2",
    // },
//     // optionTrend: "CABDCADBAC"
// ]
// export default testData;






// // WEEK 2
// const testData = [
//     {question: "In the figure above, with what minimum horizontal velocity u can a boy throw a rock at A and have it just cleared the obstruction at B ?",
//         option1: "11.2m/s",
//         option2: "14.0m/s",
//         option3: "28.0m/s",
//         option4: "60.6m/s",
//         correctAns: "28.0m/s",
//     },
//     {question: "In the figure above, Experimental data indicate that in a region downstream of a given louvered supply vent, the velocity of the emitted air is V = 0.18Vo/x, where V and x are expressed in m/s and m respectively, and Vo is the initial discharge velocity of the air. If Vo = 3.6 m/s, determine the acceleration of the air at x= 2m.",
//         option1: "+0.0153 m/s²",
//         option2: "+0.0753 m/s²",
//         option3: "-0.0525 m/s²",
//         option4: "-0.0291 m/s²",
//         correctAns: "-0.0525 m/s²",
//     },
//     {question: "In the figure above, The speed of the joger can be approximated by v=7.5(1-0.04x)^0.3 where v and x are in mi/h and miles respectively, (Given that x=0 when t=0), determine the jogger's acceleration in ft/s² at t= 0.",
//         option1: "-258E-7ft/s²",
//         option2: "-275E-6ft/s²",
//         option3: "+260E-6ft/s²",
//         option4: "-318E-9ft/s²",
//         correctAns: "-275E-6ft/s²",
//     },
//     {question: "In the figure above, The motorist enters a freeway at 45km/h and accelerates uniformly to 99km/h. From the odometer in the car, the motorist knows that she travelled 0.2km while accelerating, determine the time required to reach 99km/hr.",
//         option1: "10s",
//         option2: "7s",
//         option3: "43s",
//         option4: "18s",
//         correctAns: "10s",
//     },
//     {question: "In the figure above, In the pulley configuration shown, Cylinder A has a downward of 0.3m/s, determine the velocity of B",
//         option1: "-0.1s",
//         option2: "0.3 m/s",
//         option3: "-0.2 m/s",
//         option4: "0.5 m/s",
//         correctAns: "-0.2 m/s",
//     },
//     {question: "In the figure above, Compute the magnitude of v of the velocity of the spacecraft S to maintain a circular orbit of altitude 200 mi above the surface of the earth, (Given Gravitational constant G= 6.674*10E-11 m^3kg^-1s^-2, Mass of the Earth m= 5.972*10E24 kg, Radius of the Earth R= 3959 miles.).",
//         option1: "25,326 ft/s",
//         option2: "10,041 ft/s",
//         option3: "24018 ft/s",
//         option4: "1887 ft/s",
//         correctAns: "25,326 ft/s",
//     },
//     {question: "In the figure above, As Relay runner A enters the 20m long exchange zone with speed of 12.9m/s, he begins to slow down. Hands the baton to runner B, 1.82s later as they leave the exchange zone with the same velocity. What is the uniform acceleration of runner B ?",
//         option1: "-2.10 m/s²",
//         option2: "2.71 m/s²",
//         option3: "2.06 m/s²",
//         option4: "-2.31 m/s²",
//         correctAns: "2.06 m/s²",
//     },
//     {question: "In the figure above, The truck travels 220m in 10s while being deccelerated at a constant rate of 0.6m/s^2, determine the distance travelled during the first 1.5s.",
//         option1: "25.16 m",
//         option2: "23.91 m",
//         option3: "20.29 m",
//         option4: "36.80 m",
//         correctAns: "36.80 m",
//     },
//     {question: "In the figure above, A team of engineering students is designing a catapult to launch a small ball A so that it lands in the box. If it is known that the initial velocity vector makes a 30o angle with the horizontal, determine the range of launch speeds Vo for which the ball will land inside the box.",
//         option1: "6.01 to 6.82 m/s",
//         option2: "2.10 to 2.16 m/s",
//         option3: "6.29 to 6.81 m/s",
//         option4: "9.15 to 9.54 m/s",
//         correctAns: "6.29 to 6.81 m/s",
//     },
//     {question: "In the figure above, The 75-kg man stands on a spring scale in an elevator. During the first 3 seconds of motion from rest, the tension T in the hoisting cable is 8300 N. (Given that the total mass of the elevator, man,and scale is 750 kg), What is the reading R of the scale during this interval. ?",
//         option1: "830 N",
//         option2: "200 N",
//         option3: "432 N",
//         option4: "184 N",
//         correctAns: "830 N",
//     },
//     // optionTrend: "CABDCADBAC"
// ]
// export default testData;





// // WEEK 3
// const testData = [
//     {question: "In the figure shown, A race car C travels around the horizontal circular track that has a radius of 300 ft, If it increases it's speed at a constant rate of 7 ft/s², starting from rest, determine the time needed for it to reach an acceleration of 8 ft/s² ",
//         option1: "1.12s",
//         option2: "4.05s",
//         option3: "4.87s",
//         option4: "6.06s",
//         correctAns: "4.87s",
//     },
//     {question: "In the figure shown, The driver of the car applies her brakes to produce a uniform deceleration. Her speed is 100 km/h at the bottom A of the dip and 50 km/h at the top C of the hump, which is 120 m along the road from A. If the passengers experience a total acceleration of 3m/s² at A. If the radius of curvature at C is 150 m, calculate the radius of curvature at A.",
//         option1: "153m",
//         option2: "753m",
//         option3: "432m",
//         option4: "291m",
//         correctAns: "432m",
//     },
//     {question: "In the figure shown, At any instant the horizontal position of the weather balloon is defined by x= (8t)ft, where t is in seconds. If the equation of the path is y = x²/10, determine the magnitude and direction of the velocity when t= 2s.",
//         option1: "26.8 ft/s",
//         option2: "74.7 ft/s",
//         option3: "43.8 ft/s",
//         option4: "18.2 ft/s",
//         correctAns: "26.8 ft/s",
//     },
//     {question: "In the figure shown, The chipping machine is designed to eject wood chips at v= 25ft/s. If the tube is oriented at 30° from the horizontal, determine how high(h) the chips strike the pile if at this instant they land on the pile 20ft from the tube.",
//         option1: "1.01 ft",
//         option2: "0.30 ft",
//         option3: "1.81 ft",
//         option4: "0.52 ft",
//         correctAns: "1.81 ft",
//     },
//     {question: "In the figure shown, For a short time, the path of the plane is described by y= (0.001x²)m. If the plane is rising with a constant upward velocity of 10 m/s, determine the velocity of the plane when it reaches an altitude of y= 100 m.",
//         option1: "18.7 m/s",
//         option2: "10.4 m/s",
//         option3: "24.0 m/s",
//         option4: "88.7 m/s",
//         correctAns: "18.7 m/s",
//     },
//     {question: "In the figure shown, A train travels at a constant speed of 60mi/h and crosses over a road. If the automobile A is traveling at 45mi/h along the road, determine the velocity of the train relative to the automobile.",
//         option1: "11.0 mi/h",
//         option2: "57.1 mi/h",
//         option3: "42.5 mi/h",
//         option4: "23.1 mi/h",
//         correctAns: "42.5 mi/h",
//     },
//     {question: "In the figure shown, Determine the speed of block B if the end of the cord at A is pulled down with a speed of 2m/s.",
//         option1: "0.55m/s downwards",
//         option2: "0.10m/s upwards",
//         option3: "0.02m/s downwards",
//         option4: "0.50m/s upwards",
//         correctAns: "0.50m/s upwards",
//     },
//     {question: "In the figure shown, Determine the speed of A if B has an upward speed of 6 ft/s.",
//         option1: "24ft/s downwards",
//         option2: "20ft/s upwards",
//         option3: "43ft/s downwards",
//         option4: "18ft/s upwards",
//         correctAns: "24ft/s downwards",
//     },
//     {question: "In the figure shown, A team of engineering students designs a medium-size catapult which launches 8lb steel spheres. The launch speed is v= 80ft/s,the launch angle is 35 degrees above the horizontal, and the launch position is 6ft above ground level. The students use an athletic field with an adjoining slope topped by an 8-ft fence as shown. Determine the x-y coordinates of the point of first impact. ",
//         option1: "(101.1, 68) ft",
//         option2: "(210.5, 21) ft",
//         option3: "(164.0, 20) ft",
//         option4: "(515.7, 95) ft",
//         correctAns: "(164.0, 20) ft",
//     },
//     {question: "In the figure shown, A man at A is hoisting a safe S, by walking to the right with a constant velocity v= 0.5m/s. Determine the acceleration of the safe when it reaches the elevation of 10m. The rope is 30m long and passes over a small pulley at D.",
//         option1: "2.58mm/s² downwards",
//         option2: "3.60mm/s² upwards",
//         option3: "2.60mm/s² upwards",
//         option4: "3.18mm/s² downwards",
//         correctAns: "3.60mm/s² upwards",
//     },
// ]
// export default testData;







// WEEK 4
const testData = [
    {question: "In the figure shown, The 3kg disk D is attached to the end of a cord. The other end of the cord is attached to a ball-and-socket joint located at the center of a platform. If the platform rotates rapidly, and the disk is placed on it and released from rest as shown, determine the time it takes for the disk to reach a speed great enough to break the cord.",
        option1: "1.12s",
        option2: "4.05s",
        option3: "5.89s",
        option4: "6.06s",
        correctAns: "5.89s",
    },
    {question: "In the figure shown, The 60-kg skateboarder coasts down the circular track. If he starts from rest when theta = 0, determine the normal reaction the track exerts on him when theta = 60. Neglect his size for the calculation.",
        option1: "1.53 kN",
        option2: "7.53 kN",
        option3: "1.53 kN",
        option4: "2.91 kN",
        correctAns: "1.53 kN",
    },
    {question: "In the figure shown, The smooth 2-kg cylinder C has a pin P through it's center which passes through the slot in arm OA. If the arm is forced to rotate in the vertical plane at a constant rate theta(dot)= 0.5 rad/s, determine the force that the arm exerts on the peg at the instant theta= 60°",
        option1: "-0.356 N",
        option2: "0.747 N",
        option3: "-0.438 N",
        option4: "0.182 N",
        correctAns: "-0.356 N",
    },
    {question: "In the figure shown, The 3500-lb automobile travels down the 10° inclined road at a speed of 20 ft/s. If the driver jams on the brakes,causing his wheels to lock, determine how far s the tires skid on the road. The coefficient of kinetic friction between the wheels and the road is mk= 0.5.",
        option1: "10.1 ft",
        option2: "50.3 ft",
        option3: "19.5 ft",
        option4: "52.7 ft",
        correctAns: "19.5 ft",
    },
    {question: "In the figure shown, motor M of the hoist shown lifts the 75-lb crate C so that the acceleration of point P is 4 ft/s². Determine the power that must be supplied to the motor at the instant P has a velocity of 2 ft/s.Neglect the mass of the pulley and cable and take e= 0.85.",
        option1: "0.170 hp",
        option2: "0.104 hp",
        option3: "0.240 hp",
        option4: "0.887 hp",
        correctAns: "0.170 hp",
    },
    {question: "In the figure shown, When the skier reaches point A along the parabolic path, he has a speed of 6m/s which is increasing at 2m/s². Determine his velocity at this instant.",
        option1: "1.2 m/s",
        option2: "5.5 m/s",
        option3: "6.0 m/s",
        option4: "3.9 m/s",
        correctAns: "6.0 m/s",
    },
    {question: "In the figure shown, The boxes travel along the industrial conveyor. If a box starts from rest at A and increases it's speed such that at= (0.2t) m/s², where t is in seconds, determine it's acceleration when it arrives at p.",
        option1: "5.54 m/s²",
        option2: "1.03 m/s²",
        option3: "2.64 m/s²",
        option4: "5.36 m/s²",
        correctAns: "5.36 m/s²",
    },
    {question: "In the figure shown, The rod OA rotates in the horizontal plane such that u= (t3) rad. At the same time, the collar B is sliding outward along OA so that r = (100t²) mm. If in both cases t is in seconds, determine the velocity of the collar when t = 1s.",
        option1: "361 mm/s",
        option2: "205 mm/s",
        option3: "413 mm/s",
        option4: "185 mm/s",
        correctAns: "361 mm/s",
    },
    {question: "In the figure shown, Determine the speed of block A if block B has an upward speed of 6 ft/s",
        option1: "10ft/s Upwards",
        option2: "21ft/s Downwards",
        option3: "18ft/s Downwards",
        option4: "25ft/s Upwards",
        correctAns: "18ft/s Downwards",
    },
    {question: "In the figure shown, At the instant shown cars A and B are traveling with speeds of 18 m/s and 12 m/s, respectively. Also at this instant, A has a decrease in speed of 2 m/s², and B has an increase in speed of 3 m/s².Determine the velocity of car B with respect to car A.",
        option1: "2.58 m/s",
        option2: "9.69 m/s",
        option3: "2.60 m/s",
        option4: "3.18 m/s",
        correctAns: "9.69 m/s",
    },
]
export default testData;